// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ_XPgUnaBW9RkcjqLM7Ffu5neZEjASPo',
    appId: '1:262843547534:web:1c1a6ab151a210df6daedf',
    messagingSenderId: '262843547534',
    projectId: 'coba-flutter-firebase',
    authDomain: 'coba-flutter-firebase.firebaseapp.com',
    storageBucket: 'coba-flutter-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9J8CXxwG4NBrOlyviy8iaMADigZSeb6E',
    appId: '1:262843547534:android:3b14dec82eb0748c6daedf',
    messagingSenderId: '262843547534',
    projectId: 'coba-flutter-firebase',
    storageBucket: 'coba-flutter-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaeMFiEm0nk0Giv3y1Lc_B-AIZ4uB3RDY',
    appId: '1:262843547534:ios:7d08236de3d415246daedf',
    messagingSenderId: '262843547534',
    projectId: 'coba-flutter-firebase',
    storageBucket: 'coba-flutter-firebase.appspot.com',
    iosClientId: '262843547534-evm1qrvlq3d1i81itbhsppl6pham9uej.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyekChatting',
  );
}
